### ISSUE TITLE
New license questions

### ISSUE THREAD

**Issue by cdcme** [thomas-haslwanter/statsintro#10]
First of all, this is a phenomenal resource - thank you so much for putting this together. Regarding the license, does this mean that this repo is no longer open to contributions? Also, what license have you switched to? Thanks.

**Comment by thomas-haslwanter** [comment]
I am currently in the discussion with the publisher - who has actually provided a lot of very valuable feedback - including such things as the license ! My guess is that I will expand the IPYNB-notebooks a bit, and leave those on-line, as some kind of teaser. But I won't be able to keep the full course online.
I have really tried quite hard to see how I could publish it as an open-source book. But it would cost me about 10'000 US$ or so, which is more than I am willing to spend out of my own pocket. Also, all the online-books I have found are for real niche-areas.
Question to you: if the course remains online, do you think a significant amount of people (e.g. your library) would still buy it? If a number of people tell me so, it would be easier for me to suggest that to the publisher.
In the meantime, I will keep the archive online. Note that the PDF-file is substantially improved compared to the Web-pages, as I am currently revising the script.

**Comment by carlodicelico** [comment]
I think people would buy it. I've seen some authors have success with things like https://leanpub.com/ and https://usefedora.com/, as well, where a portion of the book or course is free and to access the rest, users have to pay. But I certainly understand going the publisher route! You stand to get a lot, including editing and marketing - it's a perfectly reasonable choice.

I was mainly asking to find out if I wanted to contribute edits and so forth, are you still (at this time) open to pull requests?

Thanks.

**Comment by thomas-haslwanter** [comment]
From my point of view - absolutely! Of course, I would also acknowledge you in the text.
Just some mistakes? Or something bigger?
From my point of view, the two things I currently miss most:
i) a better Intro into Python, without getting too long.
ii) a bridge between the Hypothesis tests, which are so common in the life sciences and in medicine, and the modeling approach, which is the standard in social sciences, econometricts, etc.

**Comment by carlodicelico** [comment]
Awesome! No, nothing major - I'm reading through it and as I notice things, I'd like to be able to contribute back, that's all. So far, just minor editorial stuff. Thanks!
